server:
 port: 9090
 
 servlet:    context-path: /my-app
spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  password: p@ssword#1
  url: jdbc:mysql://localhost:3306/tcs_db
  username: root